--- #YAML:1.0
name:                Parse-Marpa
version:             0.214.000
abstract:            (Alpha) Earley's algorithm with LR(0) precomputation
author:              
    - Jeffrey Kegler
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
no_index:
    directory:
    - inc
    - t
    - example
    - bootstrap
    - author.t
    namespace:
    - Parse::Marpa::Internal
requires:     
    Test::More:                    0
provides:
    Parse::Marpa:
        file: lib/Parse/Marpa.pm
    Parse::Marpa::Evaluator:
        file: lib/Parse/Marpa/Evaluator.pm
    Parse::Marpa::Recognizer:
        file: lib/Parse/Marpa/Recognizer.pm
    Parse::Marpa::Grammar:
        file: lib/Parse/Marpa/Grammar.pm
    Parse::Marpa::MDL:
        file: lib/Parse/Marpa/MDL.pm
    Parse::Marpa::Lex:
        file: lib/Parse/Marpa/Lex.pm
recommends:
    Test::Weaken 0.002002
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
resources:
    license: http://dev.perl.org/licenses/
