--- 
abstract: Recording and replaying CGI sessions
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::File::Cleaner: 0
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CGI-Record
no_index: 
  directory: 
    - inc
    - t
requires: 
  CGI::Capture: 0.07
  Carp: 0
  DBD::SQLite: 0
  DBI: 0
  perl: 5.005
version: 0.01
