---
abstract: 'Follow the rules in META.yml no_index keys'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: File::Find::Rule::NoIndex
name: File-Find-Rule-NoIndex
no_index:
  directory:
    - inc
    - t
requires:
  File::Find::Rule: 0.30
  File::Spec: 3.27
  Parse::CPAN::Meta: 0.04
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
