--- 
abstract: ~
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: proprietary
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: EVE-Macro
no_index: 
  directory: 
    - inc
    - t
requires: 
  Config::Tiny: 0
  File::HomeDir: 0
  File::Spec: 0
  Params::Util: 0
  Win32: 0
  Win32::GuiTest: 0
  Win32::Process: 0
  Win32::Process::List: 0
  perl: 5.6.0
version: 0.01
