---
file_add:
  - lib\Perl\Dist\WiX.pm
files_add:
  - lib\Perl\Dist\WiX\*.pm
  - lib\Perl\Dist\WiX\Base\*.pm
  - lib\Perl\Dist\WiX\Files\*.pm
  - lib\Perl\Dist\WiX\Registry\*.pm
module_name: Perl::Dist::WiX
module_version_from: lib\Perl\Dist\WiX.pm
perltidy_cfg: t\settings\perltidy.txt
site_name: csjewell.comyr.com
site_user_name: a3922569
top_dir_local: lib\Perl\Dist
top_dir_remote: /public_html/perl/Perl-Dist-WiX
build_file: Makefile.PL
url: http://csjewell.comyr.com/perl
---
-
  - '<link rev="made" href="mailto:" />'
  - '<link rev="made" href="mailto:csjewell@cpan.org" />'
-
  - '<a href="http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Perl-Dist-WiX">http://rt.cpan.org/NoAuth/ReportBug.html</a>'
  - '<a href="http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Perl-Dist-WiX" target="_top">http://rt.cpan.org/NoAuth/ReportBug.html</a>'
-
  - '<a href="mailto:mailto:bug-Perl-Dist-WiX@rt.cpan.org">'
  - '<a href="mailto:bug-Perl-Dist-WiX@rt.cpan.org">'
-
  - '<em>URI</em>'
  - '<a href="http://search.cpan.org/perldoc?URI" target="_top">URI</a>'
-
  - '<em>Process</em>'
  - '<a href="http://search.cpan.org/perldoc?Process" target="_top">Process</a>'
-
  - '<em>Readonly</em>'
  - '<a href="http://search.cpan.org/perldoc?Readonly" target="_top">Readonly</a>'
-
  - '<em>Win32</em>'
  - '<a href="http://search.cpan.org/perldoc?Win32" target="_top">Win32</a>'
-
  - '<a href="http://ali.as/">http://ali.as/</a>'
  - '<a href="http://ali.as/" target="_top">http://ali.as/</a>'
-
  - '<a href="http://csjewell.comyr.com/perl/">http://csjewell.comyr.com/perl/</a>'
  - '<a href="http://csjewell.comyr.com/perl/" target="_top">http://csjewell.comyr.com/perl/</a>'
-
  - '<link rel="stylesheet" href="code.css" type="text/css" />'
  - ''
-
  - '<body style="background-color: white">'
  - '<body>'
-
  - '<a href="http://cpan.strawberryperl.com">http://cpan.strawberryperl.com</a>'
  - '<a href="http://cpan.strawberryperl.com/" target="_top">http://cpan.strawberryperl.com</a>'
-
  - '<a href="http://strawberryperl.com/favicon.ico">http://strawberryperl.com/favicon.ico</a>'
  - http://strawberryperl.com/favicon.ico
-
  - '<a href="http://strawberryperl.com/">http://strawberryperl.com/</a>'
  - '<a href="http://strawberryperl.com/" target="_top">http://strawberryperl.com/</a>'
-
  - '</head>'
  - "<link rel=\"stylesheet\" href=\"http://csjewell.comyr.com/css/code.css\" type=\"text/css\" />\n</head>"
-
  - "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \n   \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
  - ''
-
  - '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n'
  - ''
-
  - "<?xml version=\"1.0\" ?>\n"
  - ''
-
  - '<html xmlns="http://www.w3.org/1999/xhtml">'
  - '<html>'
-
  - '<a href="http://wix.sourceforge.net/manual-wix3/wix_xsd_product.htm?">'
  - '<a href="http://wix.sourceforge.net/manual-wix3/wix_xsd_product.htm" target="_top">'
-
  - '<a href="http://wix.sourceforge.net/manual-wix3/wix_xsd_upgrade.htm">'
  - '<a href="http://wix.sourceforge.net/manual-wix3/wix_xsd_upgrade.htm" target="_top">'
-
  - '<a href="http://wix.sourceforge.net/manual-wix3/wix_xsd_product.htm">'
  - '<a href="http://wix.sourceforge.net/manual-wix3/wix_xsd_product.htm" target="_top">'
-
  - '<a href="http://wix.sourceforge.net/manual-wix3/wix_xsd_component.htm">'
  - '<a href="http://wix.sourceforge.net/manual-wix3/wix_xsd_component.htm" target="_top">'
-
  - '<a href="http://wix.sourceforge.net/manual-wix3/wix_xsd_componentref.htm">'
  - '<a href="http://wix.sourceforge.net/manual-wix3/wix_xsd_componentref.htm" target="_top">'
-
  - '<a href="/Perl/Dist/WiX.html">'
  - '<a href="http://csjewell.comyr.com/perl/WiX.pm.html">'
-
  - '<a href="/Perl/Dist/WiX.html#image_dir">'
  - '<a href="http://csjewell.comyr.com/perl/WiX.pm.html#image_dir">'
-
  - '<a href="/Perl/Dist/WiX/DirectoryTree.html">'
  - '<a href="http://csjewell.comyr.com/perl/WiX/DirectoryTree.html">'
-
  - '<a href="/Perl/Dist/WiX/Installer.html">'
  - '<a href="http://csjewell.comyr.com/perl/WiX/Installer.html">'
-
  - '<a href="/Perl/Dist/WiX/Base/Fragment.html">'
  - '<a href="http://csjewell.comyr.com/perl/WiX/Base/Fragment.html">'
-
  - '<a href="/Alien/WiX.html">'
  - '<a href="http://csjewell.comyr.com/perl/Alien-WiX/WiX.pm.html">'
-
  - '>lib\Perl\Dist\WiX\Base\'
  - '>Perl::Dist::WiX::Base::'
-
  - '>lib\Perl\Dist\WiX\Files\'
  - '>Perl::Dist::WiX::Files::'
-
  - '>lib\Perl\Dist\WiX\Registry\'
  - '>Perl::Dist::WiX::Registry::'
-
  - '>lib\Perl\Dist\WiX\'
  - '>Perl::Dist::WiX::'
-
  - '>Installer.pm<'
  - '>Perl::Dist::WiX::Installer<'
-
  - '>WiX.pm<'
  - '>Perl::Dist::WiX<'
-
  - '.pm</title>'
  - '</title>'
-
  - '.pm</h1>'
  - '</h1>'
-
  - '<a href="/LWP/Online.html">'
  - '<a href="http://search.cpan.org/perldoc/LWP%3A%3AOnline" target="_top">'
-
  - '<a href="/Module/CoreList.html">'
  - '<a href="http://search.cpan.org/perldoc/Module%3A%3ACoreList" target="_top">'
-
  - '<a href="/Math/Pari.html">'
  - '<a href="http://search.cpan.org/perldoc/Math%3A%3APari" target="_top">'
-
  - '<a href="/File/ShareDir.html">'
  - '<a href="http://search.cpan.org/perldoc/File%3A%3AShareDir" target="_top">'
-
  - '<a href="/Devel/StackTrace.html">'
  - '<a href="http://search.cpan.org/perldoc/Devel%3A%3AStackTrace" target="_top">'
-
  - '<a href="/Exception/Class.html">'
  - '<a href="http://search.cpan.org/perldoc/Exception%3A%3AClass" target="_top">'
-
  - '<a href="/IO/String.html">'
  - '<a href="http://search.cpan.org/perldoc/IO%3A%3AString" target="_top">'
-
  - '<a href="/List/MoreUtils.html">'
  - '<a href="http://search.cpan.org/perldoc/List%3A%3AMoreUtils" target="_top">'
-
  - '<a href="/Object/InsideOut.html">'
  - '<a href="http://search.cpan.org/perldoc/Object%3A%3AInsideOut" target="_top">'
-
  - '<a href="/Perl/Dist.html">'
  - '<a href="http://search.cpan.org/perldoc/Perl%3A%3ADist" target="_top">'
-
  - '<a href="/Perl/Dist/Inno.html">'
  - '<a href="http://search.cpan.org/perldoc/Perl%3A%3ADist%3A%3AInno" target="_top">'
-
  - '<a href="/Data/UUID.html">'
  - '<a href="http://search.cpan.org/perldoc/Data%3A%3AUUID" target="_top">'
-
  - '<a href="/Data/Dump/Streamer.html">'
  - '<a href="http://search.cpan.org/perldoc/Data%3A%3ADump%3A%3AStreamer" target="_top">'
-
  - '<a href="/Perl/Dist/Util/Toolchain.html">'
  - '<a href="http://search.cpan.org/perldoc/Perl%3A%3ADist%3A%3AUtil%3A%3AToolchain" target="_top">'
-
  - '<a href="/Perl/Dist/Inno/Script.html">'
  - '<a href="http://search.cpan.org/perldoc/Perl%3A%3ADist%3A%3AInno%3A%3AScript" target="_top">'
-
  - '<a href="http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Perl-Dist-WiX">http://rt.cpan.org/NoAuth/ReportBug.html</a>'
  - '<a href="http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Perl-Dist-WiX" target="_top">http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Perl-Dist-WiX</a>'

