---
abstract: ~
author: ~
distribution_type: module
generated_by: 'Module::Install version 0.68'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Win32-File-Object
no_index:
  directory:
    - inc
    - t
requires:
  Win32::File: 0.28
version: 0.01
