---
abstract: 'Add file path awareness to configuration files'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.73'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: Config::Relative
name: Config-Relative
no_index:
  directory:
    - inc
    - t
requires:
  File::HomeDir: 0.64
  File::Spec: 0.82
  Params::Util: 0.20
  perl: 5.005
version: 0.02
